[package]
name = "Burst"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
crossterm = "0.28.1"
log = "0.4.22"
rand = "0.8.5"
ratatui = "0.28.1"
tokio = { version = "1.40.0", features = ["full"] }
